#!/usr/bin/env zsh
# test-codex-migrate-to-symlinks.sh — verify migration to canonical layout.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
LAUNCHER_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
MIGRATE="$LAUNCHER_DIR/bin/codex-migrate-to-symlinks.sh"
PREPARE="$LAUNCHER_DIR/bin/codex-home-prepare.sh"

cleanup() { [[ -n "${TT:-}" && -d "$TT" ]] && rm -rf "$TT"; }
trap cleanup EXIT

[[ -x "$MIGRATE" ]] || { echo "FAIL: $MIGRATE missing"; exit 1; }
[[ -x "$PREPARE" ]] || { echo "FAIL: $PREPARE missing"; exit 1; }

TT="$(mktemp -d)"

# Case 1: legacy layout — real files where canonical expects generated/symlinked.
# Migration must back up the existing .harness/codex/ and regenerate canonically.
H1="$TT/legacy"
mkdir -p "$H1/.harness/codex/skills/copied-skill"
echo "# rules" > "$H1/CLAUDE.md"
# Manually authored config.toml without our generator header
echo "model = \"o3\"" > "$H1/.harness/codex/config.toml"
# Real directory instead of symlink — looks like an old hand-copy
echo "---
name: copied-skill
description: copied
---" > "$H1/.harness/codex/skills/copied-skill/SKILL.md"

"$MIGRATE" "$H1" >/dev/null
backup_count=$(ls -d "$H1"/.harness/codex.backup-* 2>/dev/null | wc -l | tr -d ' ')
[[ "$backup_count" -ge 1 ]] || { echo "FAIL: legacy layout was not backed up"; exit 1; }
[[ -f "$H1/.harness/codex/config.toml" ]] || { echo "FAIL: regenerated config.toml missing"; exit 1; }
head -1 "$H1/.harness/codex/config.toml" | grep -q "Generated by codex-home-prepare.sh" \
  || { echo "FAIL: regenerated config.toml lacks generator header"; exit 1; }
echo "PASS: legacy layout backed up + regenerated canonically"

# Case 2: already-canonical layout — migration is a no-op (no extra backups created).
H2="$TT/canonical"
mkdir -p "$H2"
echo "# rules" > "$H2/CLAUDE.md"
"$PREPARE" "$H2" >/dev/null
"$MIGRATE" "$H2" >/dev/null
backups=$(ls -d "$H2"/.harness/codex.backup-* 2>/dev/null | wc -l | tr -d ' ')
[[ "$backups" -eq 0 ]] || { echo "FAIL: canonical layout was unnecessarily backed up"; exit 1; }
echo "PASS: canonical layout is no-op (no spurious backup)"

# Case 3: no .harness/codex/ at all — migration must not error or create one.
H3="$TT/empty"
mkdir -p "$H3"
echo "# rules" > "$H3/CLAUDE.md"
"$MIGRATE" "$H3" >/dev/null
[[ ! -d "$H3/.harness/codex" ]] || { echo "FAIL: migrate created .harness/codex on empty harness"; exit 1; }
echo "PASS: empty harness — migrate is no-op"

# Case 4: idempotent — running twice on a legacy harness only backs up once
H4="$TT/idem"
mkdir -p "$H4/.harness/codex"
echo "# rules" > "$H4/CLAUDE.md"
echo "stale = true" > "$H4/.harness/codex/config.toml"
"$MIGRATE" "$H4" >/dev/null
sleep 1.1
"$MIGRATE" "$H4" >/dev/null
backups=$(ls -d "$H4"/.harness/codex.backup-* 2>/dev/null | wc -l | tr -d ' ')
[[ "$backups" -eq 1 ]] || { echo "FAIL: expected 1 backup, got $backups"; exit 1; }
echo "PASS: second run after migration is idempotent"

echo "✓ All codex-migrate-to-symlinks tests passed"
