#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BASH_BIN="${BASH_BIN:-$(command -v bash)}"
PREPARE="$ROOT/bin/codex-home-prepare.sh"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

FAKE_HOME="$TMP/home"
NO_MARKETPLACE="$TMP/no-marketplace"
COMPILER_TEMPLATE="$TMP/harness_compile.py"
mkdir -p "$FAKE_HOME"

cat > "$COMPILER_TEMPLATE" <<'PY'
import os
import pathlib
import sys
import time

harness = pathlib.Path(sys.argv[-1])
codex_home = harness / ".harness" / "codex"
codex_home.mkdir(parents=True, exist_ok=True)
markers = pathlib.Path(os.environ["HARNESS_TEST_COMPILER_MARKERS"])
markers.mkdir(parents=True, exist_ok=True)
mode = os.environ.get("HARNESS_TEST_COMPILER_MODE", "normal")

def wait_until(predicate, timeout=10.0):
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        if predicate():
            return
        time.sleep(0.02)
    raise SystemExit("fake compiler timed out")

if mode == "same-home":
    first = False
    try:
        fd = os.open(markers / "first-seen", os.O_CREAT | os.O_EXCL | os.O_WRONLY)
        os.close(fd)
        first = True
    except FileExistsError:
        pass

    active = markers / "active"
    owns_active = False
    try:
        active.mkdir()
        owns_active = True
    except FileExistsError:
        (markers / "overlap").touch()

    with open(markers / "calls", "a", encoding="utf-8") as stream:
        stream.write(f"{os.getpid()}\n")

    if first:
        (markers / "first-blocked").touch()
        wait_until(lambda: (markers / "release-first").exists())

    if owns_active:
        active.rmdir()
elif mode == "barrier":
    (markers / f"entered-{harness.name}").touch()
    wait_until(lambda: len(list(markers.glob("entered-*"))) == 2)
elif mode == "signal":
    original_parent = os.getppid()
    (markers / "signal-blocked").touch()
    wait_until(lambda: os.getppid() != original_parent)

(codex_home / "AGENTS.md").write_text("# generated by fake compiler\n", encoding="utf-8")
PY

make_harness() {
  local harness="$1"
  mkdir -p "$harness/core/scripts" "$harness/.claude/source"
  cp -p "$COMPILER_TEMPLATE" "$harness/core/scripts/harness_compile.py"
  : > "$harness/.claude/source/runtime-contract.yaml"
}

wait_for_file() {
  local path="$1"
  local attempts="${2:-250}"
  local i=0
  while [[ ! -e "$path" && "$i" -lt "$attempts" ]]; do
    sleep 0.02
    i=$((i + 1))
  done
  [[ -e "$path" ]]
}

# The whole per-harness mutation must be serialized. The fake compiler is
# deliberately held in the first process so a second prepare can expose an
# overlap before either process reaches config/plugin generation.
SAME_HARNESS="$TMP/same-home-harness"
SAME_MARKERS="$TMP/same-home-markers"
make_harness "$SAME_HARNESS"
mkdir -p "$SAME_MARKERS"
HOME="$FAKE_HOME" HARNESS_CODEX_BUNDLED_MARKETPLACE_SOURCE="$NO_MARKETPLACE" \
  HARNESS_TEST_COMPILER_MARKERS="$SAME_MARKERS" HARNESS_TEST_COMPILER_MODE=same-home \
  "$BASH_BIN" "$PREPARE" "$SAME_HARNESS" >"$TMP/same-a.log" 2>&1 &
same_pid_a=$!
wait_for_file "$SAME_MARKERS/first-blocked" || {
  kill "$same_pid_a" 2>/dev/null || true
  echo "FAIL: first same-home prepare never entered the fake compiler" >&2
  exit 1
}
HOME="$FAKE_HOME" HARNESS_CODEX_BUNDLED_MARKETPLACE_SOURCE="$NO_MARKETPLACE" \
  HARNESS_TEST_COMPILER_MARKERS="$SAME_MARKERS" HARNESS_TEST_COMPILER_MODE=same-home \
  "$BASH_BIN" "$PREPARE" "$SAME_HARNESS" >"$TMP/same-b.log" 2>&1 &
same_pid_b=$!
sleep 0.4
same_overlap=0
[[ -e "$SAME_MARKERS/overlap" ]] && same_overlap=1
: > "$SAME_MARKERS/release-first"
set +e
wait "$same_pid_a"; same_rc_a=$?
wait "$same_pid_b"; same_rc_b=$?
set -e
if [[ "$same_overlap" -ne 0 ]]; then
  echo "FAIL: same CODEX_HOME preparations entered the fake compiler concurrently" >&2
  exit 1
fi
[[ "$same_rc_a" -eq 0 && "$same_rc_b" -eq 0 ]] || {
  echo "FAIL: serialized same-home prepares returned $same_rc_a/$same_rc_b" >&2
  exit 1
}
[[ "$(wc -l < "$SAME_MARKERS/calls" | tr -d ' ')" == "2" ]] || {
  echo "FAIL: serialized same-home prepares must each invoke the compiler once" >&2
  exit 1
}
HOME_LOCK="$SAME_HARNESS/.harness/codex/.codex-home-prepare.lock"
[[ -f "$HOME_LOCK" ]] || {
  echo "FAIL: per-home lock file missing at $HOME_LOCK" >&2
  exit 1
}
/usr/bin/lockf -s -t 0 "$HOME_LOCK" true || {
  echo "FAIL: per-home lock remained held after both prepares exited" >&2
  exit 1
}
echo "PASS: same CODEX_HOME preparation is serialized and releases its kernel lock"

# A per-home lock must not serialize independent harness homes. Both fake
# compilers wait at a two-party barrier; a host-global preparation lock would
# make the first process time out.
DIFF_HARNESS_A="$TMP/different-home-a"
DIFF_HARNESS_B="$TMP/different-home-b"
DIFF_MARKERS="$TMP/different-home-markers"
make_harness "$DIFF_HARNESS_A"
make_harness "$DIFF_HARNESS_B"
mkdir -p "$DIFF_MARKERS"
HOME="$FAKE_HOME" HARNESS_CODEX_BUNDLED_MARKETPLACE_SOURCE="$NO_MARKETPLACE" \
  HARNESS_TEST_COMPILER_MARKERS="$DIFF_MARKERS" HARNESS_TEST_COMPILER_MODE=barrier \
  "$BASH_BIN" "$PREPARE" "$DIFF_HARNESS_A" >"$TMP/diff-a.log" 2>&1 &
diff_pid_a=$!
HOME="$FAKE_HOME" HARNESS_CODEX_BUNDLED_MARKETPLACE_SOURCE="$NO_MARKETPLACE" \
  HARNESS_TEST_COMPILER_MARKERS="$DIFF_MARKERS" HARNESS_TEST_COMPILER_MODE=barrier \
  "$BASH_BIN" "$PREPARE" "$DIFF_HARNESS_B" >"$TMP/diff-b.log" 2>&1 &
diff_pid_b=$!
set +e
wait "$diff_pid_a"; diff_rc_a=$?
wait "$diff_pid_b"; diff_rc_b=$?
set -e
[[ "$diff_rc_a" -eq 0 && "$diff_rc_b" -eq 0 ]] || {
  echo "FAIL: different CODEX_HOME prepares did not run concurrently ($diff_rc_a/$diff_rc_b)" >&2
  exit 1
}
echo "PASS: different CODEX_HOME preparations remain concurrent"

# Kernel advisory locks must self-release after a signal; no PID/mtime stale
# owner record or cleanup trap is allowed to gate the next invocation.
SIGNAL_HARNESS="$TMP/signal-home-harness"
SIGNAL_MARKERS="$TMP/signal-markers"
make_harness "$SIGNAL_HARNESS"
mkdir -p "$SIGNAL_MARKERS"
HOME="$FAKE_HOME" HARNESS_CODEX_BUNDLED_MARKETPLACE_SOURCE="$NO_MARKETPLACE" \
  HARNESS_TEST_COMPILER_MARKERS="$SIGNAL_MARKERS" HARNESS_TEST_COMPILER_MODE=signal \
  "$BASH_BIN" "$PREPARE" "$SIGNAL_HARNESS" >"$TMP/signal.log" 2>&1 &
signal_pid=$!
wait_for_file "$SIGNAL_MARKERS/signal-blocked" || {
  kill "$signal_pid" 2>/dev/null || true
  echo "FAIL: signal test never entered the fake compiler" >&2
  exit 1
}
kill -TERM "$signal_pid"
set +e
wait "$signal_pid"
set -e
SIGNAL_LOCK="$SIGNAL_HARNESS/.harness/codex/.codex-home-prepare.lock"
[[ -f "$SIGNAL_LOCK" ]] || {
  echo "FAIL: signal test did not create the per-home lock file" >&2
  exit 1
}
released=0
for _ in $(seq 1 250); do
  if /usr/bin/lockf -s -t 0 "$SIGNAL_LOCK" true; then
    released=1
    break
  fi
  sleep 0.02
done
[[ "$released" -eq 1 ]] || {
  echo "FAIL: per-home kernel lock was not released after SIGTERM" >&2
  exit 1
}
echo "PASS: SIGTERM releases the per-home preparation lock without stale cleanup"
