#!/usr/bin/env python3
"""Stable pre-project-route compiler fixture for launcher compatibility tests."""

from pathlib import Path
import sys


if len(sys.argv) != 3:
    raise SystemExit(2)

mode, root_arg = sys.argv[1:]
if mode == "--write-codex-project":
    raise SystemExit(2)
if mode != "--write-codex":
    raise SystemExit(2)

root = Path(root_arg)
runtime_source = root / ".claude" / "source" / "runtime-contract.yaml"
rule_source = root / ".claude" / "rules" / "cascading-updates.md"
if not runtime_source.is_file() or not rule_source.is_file():
    raise SystemExit(2)

agents = root / ".harness" / "codex" / "AGENTS.md"
agents.parent.mkdir(parents=True, exist_ok=True)
agents.write_text(
    "# Generated by harness_compile.py — do not edit manually.\n\n"
    '<runtime_contract id="harness-runtime-v1">\n'
    "  <source_of_truth>Claude harness source is canonical. Runtime surfaces are generated.</source_of_truth>\n"
    "</runtime_contract>\n\n"
    + rule_source.read_text(encoding="utf-8")
    + "\n<!-- BEGIN HARNESS-CODEX-RESPONSE-LANGUAGE -->\n"
    + "## Codex Response Language\n\n"
    + "- Default to Korean for conversational responses.\n"
    + "<!-- END HARNESS-CODEX-RESPONSE-LANGUAGE -->\n",
    encoding="utf-8",
)
